name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate snake game
      uses: Platane/snk@workflow
      with:
        github_user_name: MohammadAbbas393
        svg_out_path: dist/github-contribution-grid-snake.svg
